development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: localhost
  pool: 5
  username: michellemancuso
  password: 1234

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
